nohup main epinions k 0 30 >> epinions_k_0.txt
nohup main epinions k 1 30 >> epinions_k_1.txt
nohup main epinions k 2 30 >> epinions_k_2.txt
nohup main epinions k 3 30 >> epinions_k_3.txt
nohup main epinions k 4 30 >> epinions_k_4.txt
nohup main epinions k 5 30 >> epinions_k_5.txt
nohup main epinions k 7 30 >> epinions_k_7.txt
nohup main dblp k 1 30 >> dblp_k_1.txt
nohup main dblp k 2 30 >> dblp_k_2.txt
nohup main dblp k 3 30 >> dblp_k_3.txt
nohup main dblp k 4 30 >> dblp_k_4.txt
nohup main dblp k 5 30 >> dblp_k_5.txt
nohup main dblp k 7 30 >> dblp_k_7.txt
nohup main dblp k 0 30 >> dblp_k_0.txt
nohup main citation k 1 30 >> citation_k_1.txt
nohup main citation k 2 30 >> citation_k_2.txt
nohup main citation k 3 30 >> citation_k_3.txt
nohup main citation k 4 30 >> citation_k_4.txt
nohup main citation k 5 30 >> citation_k_5.txt
nohup main citation k 7 30 >> citation_k_7.txt
nohup main citation k 0 30 >> citation_k_0.txt
nohup main ciao k 2 30 >> ciao_k_2.txt
nohup main ciao k 3 30 >> ciao_k_3.txt
nohup main ciao k 4 30 >> ciao_k_4.txt
nohup main ciao k 5 30 >> ciao_k_5.txt
nohup main ciao k 7 30 >> ciao_k_7.txt
nohup main ciao k 0 30 >> ciao_k_0.txt
nohup main ciao k 1 30 >> ciao_k_1.txt
