nohup main epinions p 2 30 >> epinions_p_2.txt
nohup main epinions p 3 30 >> epinions_p_3.txt
nohup main epinions p 4 30 >> epinions_p_4.txt
nohup main epinions p 5 30 >> epinions_p_5.txt
nohup main epinions p 0 30 >> epinions_p_0.txt
nohup main epinions p 1 30 >> epinions_p_1.txt
nohup main epinions n 2 30 >> epinions_n_2.txt
nohup main epinions n 3 30 >> epinions_n_3.txt
nohup main epinions n 4 30 >> epinions_n_4.txt
nohup main epinions n 5 30 >> epinions_n_5.txt
nohup main epinions n 7 30 >> epinions_n_7.txt
nohup main epinions n 0 30 >> epinions_n_0.txt
nohup main epinions n 1 30 >> epinions_n_1.txt
nohup main dblp p 2 30 >> dblp_p_2.txt
nohup main dblp p 3 30 >> dblp_p_3.txt
nohup main dblp p 4 30 >> dblp_p_4.txt
nohup main dblp p 5 30 >> dblp_p_5.txt
nohup main dblp p 0 30 >> dblp_p_0.txt
nohup main dblp p 1 30 >> dblp_p_1.txt
nohup main dblp n 2 30 >> dblp_n_2.txt
nohup main dblp n 3 30 >> dblp_n_3.txt
nohup main dblp n 4 30 >> dblp_n_4.txt
nohup main dblp n 5 30 >> dblp_n_5.txt
nohup main dblp n 7 30 >> dblp_n_7.txt
nohup main dblp n 0 30 >> dblp_n_0.txt
nohup main dblp n 1 30 >> dblp_n_1.txt
nohup main citation p 2 30 >> citation_p_2.txt
nohup main citation p 3 30 >> citation_p_3.txt
nohup main citation p 4 30 >> citation_p_4.txt
nohup main citation p 5 30 >> citation_p_5.txt
nohup main citation p 0 30 >> citation_p_0.txt
nohup main citation p 1 30 >> citation_p_1.txt
nohup main citation n 2 30 >> citation_n_2.txt
nohup main citation n 3 30 >> citation_n_3.txt
nohup main citation n 4 30 >> citation_n_4.txt
nohup main citation n 5 30 >> citation_n_5.txt
nohup main citation n 7 30 >> citation_n_7.txt
nohup main citation n 0 30 >> citation_n_0.txt
nohup main citation n 1 30 >> citation_n_1.txt
nohup main ciao p 2 30 >> ciao_p_2.txt
nohup main ciao p 3 30 >> ciao_p_3.txt
nohup main ciao p 4 30 >> ciao_p_4.txt
nohup main ciao p 5 30 >> ciao_p_5.txt
nohup main ciao p 7 30 >> ciao_p_7.txt
nohup main ciao p 0 30 >> ciao_p_0.txt
nohup main ciao p 1 30 >> ciao_p_1.txt
nohup main ciao n 2 30 >> ciao_n_2.txt
nohup main ciao n 3 30 >> ciao_n_3.txt
nohup main ciao n 4 30 >> ciao_n_4.txt
nohup main ciao n 5 30 >> ciao_n_5.txt
nohup main ciao n 7 30 >> ciao_n_7.txt
nohup main ciao n 0 30 >> ciao_n_0.txt
nohup main ciao n 1 30 >> ciao_n_1.txt