nohup main epinions s 0 30 >> epinions_s_0.txt
nohup main epinions s 1 30 >> epinions_s_1.txt
nohup main epinions s 2 30 >> epinions_s_2.txt
nohup main epinions s 3 30 >> epinions_s_3.txt
nohup main epinions s 4 30 >> epinions_s_4.txt
nohup main epinions s 5 30 >> epinions_s_5.txt
nohup main epinions s 7 30 >> epinions_s_7.txt
nohup main dblp s 1 30 >> dblp_s_1.txt
nohup main dblp s 2 30 >> dblp_s_2.txt
nohup main dblp s 3 30 >> dblp_s_3.txt
nohup main dblp s 4 30 >> dblp_s_4.txt
nohup main dblp s 5 30 >> dblp_s_5.txt
nohup main dblp s 7 30 >> dblp_s_7.txt
nohup main dblp s 0 30 >> dblp_s_0.txt
nohup main citation s 1 30 >> citation_s_1.txt
nohup main citation s 2 30 >> citation_s_2.txt
nohup main citation s 3 30 >> citation_s_3.txt
nohup main citation s 4 30 >> citation_s_4.txt
nohup main citation s 5 30 >> citation_s_5.txt
nohup main citation s 7 30 >> citation_s_7.txt
nohup main citation s 0 30 >> citation_s_0.txt
nohup main ciao s 2 30 >> ciao_s_2.txt
nohup main ciao s 3 30 >> ciao_s_3.txt
nohup main ciao s 4 30 >> ciao_s_4.txt
nohup main ciao s 5 30 >> ciao_s_5.txt
nohup main ciao s 7 30 >> ciao_s_7.txt
nohup main ciao s 0 30 >> ciao_s_0.txt
nohup main ciao s 1 30 >> ciao_s_1.txt
